/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotPasswordImport } from './routes/auth/forgot-password'
import { Route as AppTemplateIndexImport } from './routes/app/template/index'
import { Route as AppTasksIndexImport } from './routes/app/tasks/index'
import { Route as AppNotesIndexImport } from './routes/app/notes/index'
import { Route as AppHelpIndexImport } from './routes/app/help/index'
import { Route as AppDashboardIndexImport } from './routes/app/dashboard/index'
import { Route as AppCoWorkerIndexImport } from './routes/app/co-worker/index'
import { Route as AppClientIndexImport } from './routes/app/client/index'
import { Route as AppAccountIndexImport } from './routes/app/account/index'
import { Route as AppTemplateCreateImport } from './routes/app/template/create'
import { Route as AppTasksCreateImport } from './routes/app/tasks/create'
import { Route as AppTemplateGetIdImport } from './routes/app/template/get/$id'
import { Route as AppTemplateEditIdImport } from './routes/app/template/edit/$id'
import { Route as AppNotesNoteIdImport } from './routes/app/notes/note/$id'
import { Route as AppCoWorkerGetIdImport } from './routes/app/co-worker/get/$id'
import { Route as AppClientGetIdImport } from './routes/app/client/get/$id'
import { Route as AppClientEditIdImport } from './routes/app/client/edit/$id'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const AppTemplateIndexRoute = AppTemplateIndexImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTasksIndexRoute = AppTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppNotesIndexRoute = AppNotesIndexImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppHelpIndexRoute = AppHelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardIndexRoute = AppDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCoWorkerIndexRoute = AppCoWorkerIndexImport.update({
  id: '/co-worker/',
  path: '/co-worker/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppClientIndexRoute = AppClientIndexImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAccountIndexRoute = AppAccountIndexImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTemplateCreateRoute = AppTemplateCreateImport.update({
  id: '/template/create',
  path: '/template/create',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTasksCreateRoute = AppTasksCreateImport.update({
  id: '/tasks/create',
  path: '/tasks/create',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTemplateGetIdRoute = AppTemplateGetIdImport.update({
  id: '/template/get/$id',
  path: '/template/get/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppTemplateEditIdRoute = AppTemplateEditIdImport.update({
  id: '/template/edit/$id',
  path: '/template/edit/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppNotesNoteIdRoute = AppNotesNoteIdImport.update({
  id: '/notes/note/$id',
  path: '/notes/note/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCoWorkerGetIdRoute = AppCoWorkerGetIdImport.update({
  id: '/co-worker/get/$id',
  path: '/co-worker/get/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppClientGetIdRoute = AppClientGetIdImport.update({
  id: '/client/get/$id',
  path: '/client/get/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppClientEditIdRoute = AppClientEditIdImport.update({
  id: '/client/edit/$id',
  path: '/client/edit/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/app/tasks/create': {
      id: '/app/tasks/create'
      path: '/tasks/create'
      fullPath: '/app/tasks/create'
      preLoaderRoute: typeof AppTasksCreateImport
      parentRoute: typeof AppRouteImport
    }
    '/app/template/create': {
      id: '/app/template/create'
      path: '/template/create'
      fullPath: '/app/template/create'
      preLoaderRoute: typeof AppTemplateCreateImport
      parentRoute: typeof AppRouteImport
    }
    '/app/account/': {
      id: '/app/account/'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/client/': {
      id: '/app/client/'
      path: '/client'
      fullPath: '/app/client'
      preLoaderRoute: typeof AppClientIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/co-worker/': {
      id: '/app/co-worker/'
      path: '/co-worker'
      fullPath: '/app/co-worker'
      preLoaderRoute: typeof AppCoWorkerIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/help/': {
      id: '/app/help/'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/notes/': {
      id: '/app/notes/'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/tasks/': {
      id: '/app/tasks/'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/template/': {
      id: '/app/template/'
      path: '/template'
      fullPath: '/app/template'
      preLoaderRoute: typeof AppTemplateIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/client/edit/$id': {
      id: '/app/client/edit/$id'
      path: '/client/edit/$id'
      fullPath: '/app/client/edit/$id'
      preLoaderRoute: typeof AppClientEditIdImport
      parentRoute: typeof AppRouteImport
    }
    '/app/client/get/$id': {
      id: '/app/client/get/$id'
      path: '/client/get/$id'
      fullPath: '/app/client/get/$id'
      preLoaderRoute: typeof AppClientGetIdImport
      parentRoute: typeof AppRouteImport
    }
    '/app/co-worker/get/$id': {
      id: '/app/co-worker/get/$id'
      path: '/co-worker/get/$id'
      fullPath: '/app/co-worker/get/$id'
      preLoaderRoute: typeof AppCoWorkerGetIdImport
      parentRoute: typeof AppRouteImport
    }
    '/app/notes/note/$id': {
      id: '/app/notes/note/$id'
      path: '/notes/note/$id'
      fullPath: '/app/notes/note/$id'
      preLoaderRoute: typeof AppNotesNoteIdImport
      parentRoute: typeof AppRouteImport
    }
    '/app/template/edit/$id': {
      id: '/app/template/edit/$id'
      path: '/template/edit/$id'
      fullPath: '/app/template/edit/$id'
      preLoaderRoute: typeof AppTemplateEditIdImport
      parentRoute: typeof AppRouteImport
    }
    '/app/template/get/$id': {
      id: '/app/template/get/$id'
      path: '/template/get/$id'
      fullPath: '/app/template/get/$id'
      preLoaderRoute: typeof AppTemplateGetIdImport
      parentRoute: typeof AppRouteImport
    }
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppTasksCreateRoute: typeof AppTasksCreateRoute
  AppTemplateCreateRoute: typeof AppTemplateCreateRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppClientIndexRoute: typeof AppClientIndexRoute
  AppCoWorkerIndexRoute: typeof AppCoWorkerIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppHelpIndexRoute: typeof AppHelpIndexRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppTemplateIndexRoute: typeof AppTemplateIndexRoute
  AppClientEditIdRoute: typeof AppClientEditIdRoute
  AppClientGetIdRoute: typeof AppClientGetIdRoute
  AppCoWorkerGetIdRoute: typeof AppCoWorkerGetIdRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppTemplateEditIdRoute: typeof AppTemplateEditIdRoute
  AppTemplateGetIdRoute: typeof AppTemplateGetIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTasksCreateRoute: AppTasksCreateRoute,
  AppTemplateCreateRoute: AppTemplateCreateRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppClientIndexRoute: AppClientIndexRoute,
  AppCoWorkerIndexRoute: AppCoWorkerIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppHelpIndexRoute: AppHelpIndexRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppTemplateIndexRoute: AppTemplateIndexRoute,
  AppClientEditIdRoute: AppClientEditIdRoute,
  AppClientGetIdRoute: AppClientGetIdRoute,
  AppCoWorkerGetIdRoute: AppCoWorkerGetIdRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppTemplateEditIdRoute: AppTemplateEditIdRoute,
  AppTemplateGetIdRoute: AppTemplateGetIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/tasks/create': typeof AppTasksCreateRoute
  '/app/template/create': typeof AppTemplateCreateRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/client': typeof AppClientIndexRoute
  '/app/co-worker': typeof AppCoWorkerIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/help': typeof AppHelpIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/tasks': typeof AppTasksIndexRoute
  '/app/template': typeof AppTemplateIndexRoute
  '/app/client/edit/$id': typeof AppClientEditIdRoute
  '/app/client/get/$id': typeof AppClientGetIdRoute
  '/app/co-worker/get/$id': typeof AppCoWorkerGetIdRoute
  '/app/notes/note/$id': typeof AppNotesNoteIdRoute
  '/app/template/edit/$id': typeof AppTemplateEditIdRoute
  '/app/template/get/$id': typeof AppTemplateGetIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/tasks/create': typeof AppTasksCreateRoute
  '/app/template/create': typeof AppTemplateCreateRoute
  '/app/account': typeof AppAccountIndexRoute
  '/app/client': typeof AppClientIndexRoute
  '/app/co-worker': typeof AppCoWorkerIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/help': typeof AppHelpIndexRoute
  '/app/notes': typeof AppNotesIndexRoute
  '/app/tasks': typeof AppTasksIndexRoute
  '/app/template': typeof AppTemplateIndexRoute
  '/app/client/edit/$id': typeof AppClientEditIdRoute
  '/app/client/get/$id': typeof AppClientGetIdRoute
  '/app/co-worker/get/$id': typeof AppCoWorkerGetIdRoute
  '/app/notes/note/$id': typeof AppNotesNoteIdRoute
  '/app/template/edit/$id': typeof AppTemplateEditIdRoute
  '/app/template/get/$id': typeof AppTemplateGetIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/app/tasks/create': typeof AppTasksCreateRoute
  '/app/template/create': typeof AppTemplateCreateRoute
  '/app/account/': typeof AppAccountIndexRoute
  '/app/client/': typeof AppClientIndexRoute
  '/app/co-worker/': typeof AppCoWorkerIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/help/': typeof AppHelpIndexRoute
  '/app/notes/': typeof AppNotesIndexRoute
  '/app/tasks/': typeof AppTasksIndexRoute
  '/app/template/': typeof AppTemplateIndexRoute
  '/app/client/edit/$id': typeof AppClientEditIdRoute
  '/app/client/get/$id': typeof AppClientGetIdRoute
  '/app/co-worker/get/$id': typeof AppCoWorkerGetIdRoute
  '/app/notes/note/$id': typeof AppNotesNoteIdRoute
  '/app/template/edit/$id': typeof AppTemplateEditIdRoute
  '/app/template/get/$id': typeof AppTemplateGetIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/tasks/create'
    | '/app/template/create'
    | '/app/account'
    | '/app/client'
    | '/app/co-worker'
    | '/app/dashboard'
    | '/app/help'
    | '/app/notes'
    | '/app/tasks'
    | '/app/template'
    | '/app/client/edit/$id'
    | '/app/client/get/$id'
    | '/app/co-worker/get/$id'
    | '/app/notes/note/$id'
    | '/app/template/edit/$id'
    | '/app/template/get/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/tasks/create'
    | '/app/template/create'
    | '/app/account'
    | '/app/client'
    | '/app/co-worker'
    | '/app/dashboard'
    | '/app/help'
    | '/app/notes'
    | '/app/tasks'
    | '/app/template'
    | '/app/client/edit/$id'
    | '/app/client/get/$id'
    | '/app/co-worker/get/$id'
    | '/app/notes/note/$id'
    | '/app/template/edit/$id'
    | '/app/template/get/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/app/tasks/create'
    | '/app/template/create'
    | '/app/account/'
    | '/app/client/'
    | '/app/co-worker/'
    | '/app/dashboard/'
    | '/app/help/'
    | '/app/notes/'
    | '/app/tasks/'
    | '/app/template/'
    | '/app/client/edit/$id'
    | '/app/client/get/$id'
    | '/app/co-worker/get/$id'
    | '/app/notes/note/$id'
    | '/app/template/edit/$id'
    | '/app/template/get/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/auth/forgot-password",
        "/auth/login",
        "/auth/register",
        "/auth/reset-password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/tasks/create",
        "/app/template/create",
        "/app/account/",
        "/app/client/",
        "/app/co-worker/",
        "/app/dashboard/",
        "/app/help/",
        "/app/notes/",
        "/app/tasks/",
        "/app/template/",
        "/app/client/edit/$id",
        "/app/client/get/$id",
        "/app/co-worker/get/$id",
        "/app/notes/note/$id",
        "/app/template/edit/$id",
        "/app/template/get/$id"
      ]
    },
    "/auth/forgot-password": {
      "filePath": "auth/forgot-password.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/app/tasks/create": {
      "filePath": "app/tasks/create.tsx",
      "parent": "/app"
    },
    "/app/template/create": {
      "filePath": "app/template/create.tsx",
      "parent": "/app"
    },
    "/app/account/": {
      "filePath": "app/account/index.tsx",
      "parent": "/app"
    },
    "/app/client/": {
      "filePath": "app/client/index.tsx",
      "parent": "/app"
    },
    "/app/co-worker/": {
      "filePath": "app/co-worker/index.tsx",
      "parent": "/app"
    },
    "/app/dashboard/": {
      "filePath": "app/dashboard/index.tsx",
      "parent": "/app"
    },
    "/app/help/": {
      "filePath": "app/help/index.tsx",
      "parent": "/app"
    },
    "/app/notes/": {
      "filePath": "app/notes/index.tsx",
      "parent": "/app"
    },
    "/app/tasks/": {
      "filePath": "app/tasks/index.tsx",
      "parent": "/app"
    },
    "/app/template/": {
      "filePath": "app/template/index.tsx",
      "parent": "/app"
    },
    "/app/client/edit/$id": {
      "filePath": "app/client/edit/$id.tsx",
      "parent": "/app"
    },
    "/app/client/get/$id": {
      "filePath": "app/client/get/$id.tsx",
      "parent": "/app"
    },
    "/app/co-worker/get/$id": {
      "filePath": "app/co-worker/get/$id.tsx",
      "parent": "/app"
    },
    "/app/notes/note/$id": {
      "filePath": "app/notes/note/$id.tsx",
      "parent": "/app"
    },
    "/app/template/edit/$id": {
      "filePath": "app/template/edit/$id.tsx",
      "parent": "/app"
    },
    "/app/template/get/$id": {
      "filePath": "app/template/get/$id.tsx",
      "parent": "/app"
    }
  }
}
ROUTE_MANIFEST_END */
